development:
  adapter: postgresql
  database: photoviewer_api
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: photoviewer_api_test
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: photoviewer_api
  pool: 5
  timeout: 5000
  host: localhost